# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-vault" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "f8ca005d33d8109aa95c860f7bf15dfb1dc8ee7b7f4a351c99fb682a477fe6ba"
      url "https://github.com/roman-16/git-vault/releases/download/v#{version}/git-vault_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8f41ddba30edd317f9838f25a6decf7cf0554bc79468370853fd2da040d391d8"
      url "https://github.com/roman-16/git-vault/releases/download/v#{version}/git-vault_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c7a7fca91cdc6c11236320338ad9a574162932008bca6ca00ddab46005de58a5"
      url "https://github.com/roman-16/git-vault/releases/download/v#{version}/git-vault_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "48ac0c933899ba54ce4b235fe525d996b45947bee352f57e5736fbe384463e3e"
      url "https://github.com/roman-16/git-vault/releases/download/v#{version}/git-vault_#{version}_linux_arm64.tar.gz"
    end
  end

  name "git-vault"
  desc "Transparent encryption for git that collapses everything it protects into one opaque file"
  homepage "https://github.com/roman-16/git-vault"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-vault"
  manpage "man/git-vault.1"
  bash_completion "completions/git-vault.bash"
  fish_completion "completions/git-vault.fish"
  zsh_completion "completions/git-vault.zsh"

  # No zap stanza required

end
