# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-vault" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "82ba3823bf8ec667a4bf4645686789a6112be5687d896f43b4264686905af5ed"
      url "https://github.com/roman-16/git-vault/releases/download/v#{version}/git-vault_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8b7d366456df4494e2f132c6be916c9374b96acb8062d11050e325799f0fbfe4"
      url "https://github.com/roman-16/git-vault/releases/download/v#{version}/git-vault_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2535668e6cff2942b7fdfc3c891f5da232804e1bc9f35a710165490e6b2fb7d2"
      url "https://github.com/roman-16/git-vault/releases/download/v#{version}/git-vault_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a3f94f3c96a898858a7cf597971ef0bf8ebec3d8496b32b96c330191d78a3eb5"
      url "https://github.com/roman-16/git-vault/releases/download/v#{version}/git-vault_#{version}_linux_arm64.tar.gz"
    end
  end

  name "git-vault"
  desc "Transparent encryption for git that collapses everything it protects into one opaque file"
  homepage "https://github.com/roman-16/git-vault"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-vault"
  manpage "man/git-vault.1"
  bash_completion "completions/git-vault.bash"
  fish_completion "completions/git-vault.fish"
  zsh_completion "completions/git-vault.zsh"

  # No zap stanza required

end
