# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-vault" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "ffd9bfa9df3533a2ad065528a6669223f3859fade43a09d7d9e22683f644b44d"
      url "https://github.com/roman-16/git-vault/releases/download/v#{version}/git-vault_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9748b619148c297572d08908a1a02de8d428f14a1b021b8ccd0808b5753bb1e1"
      url "https://github.com/roman-16/git-vault/releases/download/v#{version}/git-vault_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b9d48c4b276f71338efaa1c1c6916d6f39195733a43fd91e4c496043e3b1a383"
      url "https://github.com/roman-16/git-vault/releases/download/v#{version}/git-vault_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f43feb0fffbd6cdef97548d3c3e823edcb5b298e20739f46ff737b5826d11bd2"
      url "https://github.com/roman-16/git-vault/releases/download/v#{version}/git-vault_#{version}_linux_arm64.tar.gz"
    end
  end

  name "git-vault"
  desc "Transparent encryption for git that collapses everything it protects into one opaque file"
  homepage "https://github.com/roman-16/git-vault"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-vault"
  manpage "man/git-vault.1"
  bash_completion "completions/git-vault.bash"
  fish_completion "completions/git-vault.fish"
  zsh_completion "completions/git-vault.zsh"

  # No zap stanza required

end
