# This file was generated by GoReleaser. DO NOT EDIT.
cask "proton-cli" do
  version "2.2.1"

  on_macos do
    on_intel do
      sha256 "f1c13eb84ac1faf6b144c7ffc0863ab5ffe636a70f8c7c05340572a9e1ba1d29"
      url "https://github.com/roman-16/proton-cli/releases/download/v#{version}/proton-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "95e782587de326e41abe138c0d251d56ddc1599456a476c68a24fa2cd56d76c1"
      url "https://github.com/roman-16/proton-cli/releases/download/v#{version}/proton-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "54a1d05115f28508f2dc7fabd17d6047f5e86456d1f771c329d1f3a70ac84ae9"
      url "https://github.com/roman-16/proton-cli/releases/download/v#{version}/proton-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b2ae856fa287cb36e9c4d34227f6e50f46713180b890921dd54bf887244a6b82"
      url "https://github.com/roman-16/proton-cli/releases/download/v#{version}/proton-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "proton-cli"
  desc "Unofficial, end-to-end encrypted CLI for Proton Mail, Drive, Calendar, Pass and Contacts."
  homepage "https://github.com/roman-16/proton-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "proton-cli"
  bash_completion "completions/proton-cli.bash"
  fish_completion "completions/proton-cli.fish"
  zsh_completion "completions/proton-cli.zsh"

  # No zap stanza required

end
