# This file was generated by GoReleaser. DO NOT EDIT.
cask "proton-cli" do
  version "1.9.10"

  on_macos do
    on_intel do
      sha256 "8d16cf7060067a2d1f15b8fc44d3efd4f74be99c274e6d22cf8a48d2917f6205"
      url "https://github.com/roman-16/proton-cli/releases/download/v#{version}/proton-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "205f0f746fcb99fdc9f5ce7a0e234effb7dd2d938201b966ab537c922bd88b9d"
      url "https://github.com/roman-16/proton-cli/releases/download/v#{version}/proton-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5f4da8dd31ea4b786c184e652584a838bc9d1743b36f94479f898f0a4833cd1c"
      url "https://github.com/roman-16/proton-cli/releases/download/v#{version}/proton-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e31c8d48540f3684e2643fc8187a7c5b6fc2b211a9838172d6732b9b1eb013e5"
      url "https://github.com/roman-16/proton-cli/releases/download/v#{version}/proton-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "proton-cli"
  desc "An unofficial command-line tool for Proton - Mail, Drive, Calendar, Pass, and Contacts from your terminal, with real end-to-end encryption."
  homepage "https://github.com/roman-16/proton-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "proton-cli"
  bash_completion "completions/proton-cli.bash"
  fish_completion "completions/proton-cli.fish"
  zsh_completion "completions/proton-cli.zsh"

  # No zap stanza required

end
