# This file was generated by GoReleaser. DO NOT EDIT.
cask "proton-cli" do
  binary "proton", target: "proton-cli"
  fish_completion "completions/proton-cli.fish"

  version "4.2.3"

  on_macos do
    on_arm do
      sha256 "6d56553eb4b8cc8703a66c3bab33285f434d4d1879410c75198aa47f75477463"
      url "https://github.com/roman-16/proton-cli/releases/download/v#{version}/proton-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0a16f31f3e5960500c7475f6972b92efd1804714194f3c1f3d5c53aaa0e5ea38"
      url "https://github.com/roman-16/proton-cli/releases/download/v#{version}/proton-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e426d72861496f3a7433f883c8c7ca55f8ce75a136d9adb81445c51431dd7ae6"
      url "https://github.com/roman-16/proton-cli/releases/download/v#{version}/proton-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5366cefcf226c6da6f5d0618aa50416c72cad0cad018ac60744460bb5e279be1"
      url "https://github.com/roman-16/proton-cli/releases/download/v#{version}/proton-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "proton-cli"
  desc "Unofficial, end-to-end encrypted CLI for Proton Mail, Drive, Calendar, Pass and Contacts."
  homepage "https://github.com/roman-16/proton-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "proton"
  bash_completion "completions/proton.bash"
  fish_completion "completions/proton.fish"
  zsh_completion "completions/proton.zsh"

  # No zap stanza required
end
