# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProtonCli < Formula
  desc "An unofficial command-line tool for Proton - Mail, Drive, Calendar, Pass, and Contacts from your terminal, with real end-to-end encryption."
  homepage "https://github.com/roman-16/proton-cli"
  version "1.9.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roman-16/proton-cli/releases/download/v1.9.6/proton-cli_1.9.6_darwin_amd64.tar.gz"
      sha256 "fe3eab2f2f345a3aae327a381db01a8649febd06e210de1b90bb6d42074332bf"

      define_method(:install) do
        bin.install "proton-cli"
        bash_completion.install "completions/proton-cli.bash" => "proton-cli"
        fish_completion.install "completions/proton-cli.fish"
        zsh_completion.install "completions/proton-cli.zsh" => "_proton-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/roman-16/proton-cli/releases/download/v1.9.6/proton-cli_1.9.6_darwin_arm64.tar.gz"
      sha256 "d27d3a71ad5b848d4610abb6839256bc7e534b4c9d1c156ad11841a76e3b07eb"

      define_method(:install) do
        bin.install "proton-cli"
        bash_completion.install "completions/proton-cli.bash" => "proton-cli"
        fish_completion.install "completions/proton-cli.fish"
        zsh_completion.install "completions/proton-cli.zsh" => "_proton-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/roman-16/proton-cli/releases/download/v1.9.6/proton-cli_1.9.6_linux_amd64.tar.gz"
      sha256 "f5914a8d427b263921139130a917768cfc9a5e39abe9aee8daba1ab264be780d"
      define_method(:install) do
        bin.install "proton-cli"
        bash_completion.install "completions/proton-cli.bash" => "proton-cli"
        fish_completion.install "completions/proton-cli.fish"
        zsh_completion.install "completions/proton-cli.zsh" => "_proton-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/roman-16/proton-cli/releases/download/v1.9.6/proton-cli_1.9.6_linux_arm64.tar.gz"
      sha256 "4845c3e36aac6b74aed6b6f93d48c15a8623273bdcdb39298246643c6f4e69a8"
      define_method(:install) do
        bin.install "proton-cli"
        bash_completion.install "completions/proton-cli.bash" => "proton-cli"
        fish_completion.install "completions/proton-cli.fish"
        zsh_completion.install "completions/proton-cli.zsh" => "_proton-cli"
      end
    end
  end

  test do
    system "#{bin}/proton-cli", "--version"
  end
end
